# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://8077.github.io
date_format: "ordinal"
title: 马走田
subtitle: "搬码, 搬码, 你不要睡觉啦"
description: "马记"
keywords: 马记, 8077, Alex Ma
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/8077/8077.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Alex Ma
organization: Hewlett Packard Enterprise
organization_url: https://www.hpe.com
location: Shanghai, China
email: junshan.ma@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: 8077
#douban_username: xxx
#facebook_username: xxx
weibo_username: 斯莫维尔
#zhihu_username: xxx
#twitter_username: xxx

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
#duoshuo_username: xxx
disqus_username: 0877

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Python, Django, Selenium, Robot Framework]
# skill_mobile_app_keywords: [xx, xx]
# skill_windows_keywords: [xx, xx]
